package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.PartComputer;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PartComputerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PART_COMPUTER
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    int insert(PartComputer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PART_COMPUTER
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    List<PartComputer> selectAll();
}