package lt.vu.mybatis.model;

import java.util.Date;

public class Computer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPUTER.ID
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPUTER.BUILD_DATE
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    private Date buildDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPUTER.HEIGHT
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    private Integer height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPUTER.LENGTH
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    private Integer length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPUTER.NAME
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPUTER.WARRANTY_END_DATE
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    private Date warrantyEndDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPUTER.ID
     *
     * @return the value of PUBLIC.COMPUTER.ID
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPUTER.ID
     *
     * @param id the value for PUBLIC.COMPUTER.ID
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPUTER.BUILD_DATE
     *
     * @return the value of PUBLIC.COMPUTER.BUILD_DATE
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    public Date getBuildDate() {
        return buildDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPUTER.BUILD_DATE
     *
     * @param buildDate the value for PUBLIC.COMPUTER.BUILD_DATE
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    public void setBuildDate(Date buildDate) {
        this.buildDate = buildDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPUTER.HEIGHT
     *
     * @return the value of PUBLIC.COMPUTER.HEIGHT
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPUTER.HEIGHT
     *
     * @param height the value for PUBLIC.COMPUTER.HEIGHT
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPUTER.LENGTH
     *
     * @return the value of PUBLIC.COMPUTER.LENGTH
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    public Integer getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPUTER.LENGTH
     *
     * @param length the value for PUBLIC.COMPUTER.LENGTH
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    public void setLength(Integer length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPUTER.NAME
     *
     * @return the value of PUBLIC.COMPUTER.NAME
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPUTER.NAME
     *
     * @param name the value for PUBLIC.COMPUTER.NAME
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPUTER.WARRANTY_END_DATE
     *
     * @return the value of PUBLIC.COMPUTER.WARRANTY_END_DATE
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    public Date getWarrantyEndDate() {
        return warrantyEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPUTER.WARRANTY_END_DATE
     *
     * @param warrantyEndDate the value for PUBLIC.COMPUTER.WARRANTY_END_DATE
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    public void setWarrantyEndDate(Date warrantyEndDate) {
        this.warrantyEndDate = warrantyEndDate;
    }
}