package lt.vu.mybatis.model;

import lombok.Getter;
import lombok.Setter;
import lt.vu.entities.Part;

import java.util.Date;
import java.util.List;

public class Computer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPUTER.ID
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPUTER.BRANDNAME
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    private Integer brandname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPUTER.BUILD_DATE
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    private Date buildDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPUTER.NAME
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPUTER.WARRANTY_END_DATE
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    private Date warrantyEndDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPUTER.ID
     *
     * @return the value of PUBLIC.COMPUTER.ID
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPUTER.ID
     *
     * @param id the value for PUBLIC.COMPUTER.ID
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPUTER.BRANDNAME
     *
     * @return the value of PUBLIC.COMPUTER.BRANDNAME
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    public Integer getBrandname() {
        return brandname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPUTER.BRANDNAME
     *
     * @param brandname the value for PUBLIC.COMPUTER.BRANDNAME
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    public void setBrandname(Integer brandname) {
        this.brandname = brandname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPUTER.BUILD_DATE
     *
     * @return the value of PUBLIC.COMPUTER.BUILD_DATE
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    public Date getBuildDate() {
        return buildDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPUTER.BUILD_DATE
     *
     * @param buildDate the value for PUBLIC.COMPUTER.BUILD_DATE
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    public void setBuildDate(Date buildDate) {
        this.buildDate = buildDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPUTER.NAME
     *
     * @return the value of PUBLIC.COMPUTER.NAME
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPUTER.NAME
     *
     * @param name the value for PUBLIC.COMPUTER.NAME
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPUTER.WARRANTY_END_DATE
     *
     * @return the value of PUBLIC.COMPUTER.WARRANTY_END_DATE
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    public Date getWarrantyEndDate() {
        return warrantyEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPUTER.WARRANTY_END_DATE
     *
     * @param warrantyEndDate the value for PUBLIC.COMPUTER.WARRANTY_END_DATE
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    public void setWarrantyEndDate(Date warrantyEndDate) {
        this.warrantyEndDate = warrantyEndDate;
    }

   @Getter
    @Setter
    private List<lt.vu.entities.Part> parts;

    public List<Part> getParts(){ return parts;}
}