package lt.vu.mybatis.model;

public class PartComputer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PART_COMPUTER.PARTS_ID
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    private Integer partsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PART_COMPUTER.COMPUTERS_ID
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    private Integer computersId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PART_COMPUTER.PARTS_ID
     *
     * @return the value of PUBLIC.PART_COMPUTER.PARTS_ID
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    public Integer getPartsId() {
        return partsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PART_COMPUTER.PARTS_ID
     *
     * @param partsId the value for PUBLIC.PART_COMPUTER.PARTS_ID
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    public void setPartsId(Integer partsId) {
        this.partsId = partsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PART_COMPUTER.COMPUTERS_ID
     *
     * @return the value of PUBLIC.PART_COMPUTER.COMPUTERS_ID
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    public Integer getComputersId() {
        return computersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PART_COMPUTER.COMPUTERS_ID
     *
     * @param computersId the value for PUBLIC.PART_COMPUTER.COMPUTERS_ID
     *
     * @mbg.generated Tue May 11 11:49:17 EEST 2021
     */
    public void setComputersId(Integer computersId) {
        this.computersId = computersId;
    }
}