package lt.vu.mybatis.model;

public class Part {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PART.ID
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PART.NAME
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PART.PRICE
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PART.PRODUCTID
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    private Integer productid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PART.ID
     *
     * @return the value of PUBLIC.PART.ID
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PART.ID
     *
     * @param id the value for PUBLIC.PART.ID
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PART.NAME
     *
     * @return the value of PUBLIC.PART.NAME
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PART.NAME
     *
     * @param name the value for PUBLIC.PART.NAME
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PART.PRICE
     *
     * @return the value of PUBLIC.PART.PRICE
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PART.PRICE
     *
     * @param price the value for PUBLIC.PART.PRICE
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PART.PRODUCTID
     *
     * @return the value of PUBLIC.PART.PRODUCTID
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PART.PRODUCTID
     *
     * @param productid the value for PUBLIC.PART.PRODUCTID
     *
     * @mbg.generated Tue May 04 01:43:36 EEST 2021
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }
}